In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import classification_report

from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split , cross_val_score

import warnings
warnings.filterwarnings('ignore')


In [2]:
df=pd.read_csv('forestfires.csv')
df.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [4]:
df.dtypes

month             object
day               object
FFMC             float64
DMC              float64
DC               float64
ISI              float64
temp             float64
RH                 int64
wind             float64
rain             float64
area             float64
dayfri             int64
daymon             int64
daysat             int64
daysun             int64
daythu             int64
daytue             int64
daywed             int64
monthapr           int64
monthaug           int64
monthdec           int64
monthfeb           int64
monthjan           int64
monthjul           int64
monthjun           int64
monthmar           int64
monthmay           int64
monthnov           int64
monthoct           int64
monthsep           int64
size_category     object
dtype: object

In [5]:
df.shape

(517, 31)

In [6]:
df[df.duplicated()].shape

(8, 31)

In [7]:
df1=df.copy()

In [8]:
df1[df1.duplicated()]

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
53    aug  wed  92.1  111.2  654.1   9.6  20.4  42   4.9   0.0  ...         0   
100   aug  sun  91.4  142.4  601.4  10.6  19.8  39   5.4   0.0  ...         0   
215   mar  sat  91.7   35.8   80.8   7.8  17.0  27   4.9   0.0  ...         0   
303   jun  fri  91.1   94.1  232.1   7.1  19.2  38   4.5   0.0  ...         0   
426   aug  thu  91.6  248.4  753.8   6.3  20.4  56   2.2   0.0  ...         0   
461   aug  sat  93.7  231.1  715.1   8.4  18.9  64   4.9   0.0  ...         0   
501   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8  ...         0   
508   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
53          0         0         0         0         0         0         0   
100         0         0         0         0         0         0         0   
215         0         0         0         1         0         0         0   
303         0         0         1         0         0         0         0   
426         0         0         0         0         0         0         0   
461         0         0         0         0         0         0         0   
501         0         0         0         0         0         0         0   
508         0         0         0         0         0         0         0   

     monthsep  size_category  
53          0          small  
100         0          small  
215         0          large  
303         0          small  
426         0          small  
461         0          small  
501         0          small  
508         0          small  

[8 rows x 31 columns]

In [9]:
df5=df1.drop_duplicates()

In [10]:
df5.shape

(509, 31)

In [11]:
df5[df5.duplicated()].shape

(0, 31)

In [12]:
df5.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

In [13]:
df5.size_category.replace(('small','large'),(0,1),inplace=True)
df5.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0              0  
1         0              0  
2         0              0  
3         0              0  
4         0              0  

[5 rows x 31 columns]

In [14]:
scaler=StandardScaler()
scaler_df2=scaler.fit_transform(df5.iloc[:,2:])
scaler_df2

array([[-7.96039810e-01, -1.31838569e+00, -1.82893094e+00, ...,
        -1.74253759e-01, -7.14412875e-01, -6.09891511e-01],
       [-3.25665522e-03, -1.17405250e+00,  4.89256926e-01, ...,
         5.73875712e+00, -7.14412875e-01, -6.09891511e-01],
       [-3.25665522e-03, -1.04383887e+00,  5.61044929e-01, ...,
         5.73875712e+00, -7.14412875e-01, -6.09891511e-01],
       ...,
       [-1.62485856e+00, -8.39889805e-01,  4.75141308e-01, ...,
        -1.74253759e-01, -7.14412875e-01,  1.63963587e+00],
       [ 6.81419706e-01,  5.61083388e-01,  2.69859884e-01, ...,
        -1.74253759e-01, -7.14412875e-01, -6.09891511e-01],
       [-2.00323234e+00, -1.68235633e+00, -1.77892132e+00, ...,
        -1.74253759e-01, -7.14412875e-01, -6.09891511e-01]])

In [15]:
X=df5.iloc[:,2:30]
X


FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  ...  \
0    86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1  ...   
1    90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0  ...   
2    90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0  ...   
3    91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1  ...   
4    89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0  ...   
..    ...    ...    ...   ...   ...  ..   ...   ...    ...     ...  ...   
512  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0  ...   
513  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0  ...   
514  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0  ...   
515  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0  ...   
516  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0  ...   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep  
0           0         0         0  
1           0         1         0  
2           0         1         0  
3           0         0         0  
4           0         0         0  
..        ...       ...       ...  
512         0         0         0  
513         0         0         0  
514         0         0         0  
515         0         0         0  
516         1         0         0  

[509 rows x 28 columns]

In [16]:
scaler=StandardScaler()
Z=scaler.fit_transform(X)
Z

array([[-7.96039810e-01, -1.31838569e+00, -1.82893094e+00, ...,
        -4.43678255e-02, -1.74253759e-01, -7.14412875e-01],
       [-3.25665522e-03, -1.17405250e+00,  4.89256926e-01, ...,
        -4.43678255e-02,  5.73875712e+00, -7.14412875e-01],
       [-3.25665522e-03, -1.04383887e+00,  5.61044929e-01, ...,
        -4.43678255e-02,  5.73875712e+00, -7.14412875e-01],
       ...,
       [-1.62485856e+00, -8.39889805e-01,  4.75141308e-01, ...,
        -4.43678255e-02, -1.74253759e-01, -7.14412875e-01],
       [ 6.81419706e-01,  5.61083388e-01,  2.69859884e-01, ...,
        -4.43678255e-02, -1.74253759e-01, -7.14412875e-01],
       [-2.00323234e+00, -1.68235633e+00, -1.77892132e+00, ...,
         2.25388553e+01, -1.74253759e-01, -7.14412875e-01]])

In [17]:
y=df5.iloc[:,-1:]
y

size_category
0                0
1                0
2                0
3                0
4                0
..             ...
512              1
513              1
514              1
515              0
516              0

[509 rows x 1 columns]

In [18]:
X_train,X_test,y_train,y_test=train_test_split(Z,y,test_size=0.2)


In [19]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((407, 28), (102, 28), (407, 1), (102, 1))



# USing GridSearch

In [20]:

from sklearn.model_selection import GridSearchCV
clf=SVC()
data_grid=[{'kernel':['rbf'],'gamma':[50,10,5,0.05],'C':[0.1,0.2,0.3,0.6]}
          ]
gsv=GridSearchCV(clf,data_grid,cv=10)


In [21]:
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [0.1, 0.2, 0.3, 0.6], 'gamma': [50, 10, 5, 0.05],
                          'kernel': ['rbf']}])

In [36]:
gsv.best_params_,gsv.best_score_

({'C': 0.8, 'kernel': 'linear'}, 0.8821341463414635)

In [37]:
clf1 = SVC(C=0.6,gamma=45)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 80.3921568627451


array([[77,  1],
       [19,  5]], dtype=int64)

In [29]:
data_grid=[{'kernel':['linear'],'C':[0.1,0.2,0.3,0.8]}]
gsv=GridSearchCV(clf,data_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(C=0.4),
             param_grid=[{'C': [0.1, 0.2, 0.3, 0.8], 'kernel': ['linear']}])

In [33]:
gsv.best_params_,gsv.best_score_


({'C': 0.8, 'kernel': 'linear'}, 0.8821341463414635)

In [34]:
clf = SVC(C=0.8)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 80.3921568627451


array([[77,  1],
       [19,  5]], dtype=int64)

In [39]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[77  1]
 [19  5]]
              precision    recall  f1-score   support

           0       0.80      0.99      0.89        78
           1       0.83      0.21      0.33        24

    accuracy                           0.80       102
   macro avg       0.82      0.60      0.61       102
weighted avg       0.81      0.80      0.76       102



# Polynomial

In [47]:
clf_poly=SVC(kernel='poly',degree=1)
clf_poly.fit(X_train,y_train)

SVC(degree=1, kernel='poly')

In [48]:
y_pred_poly=clf_poly.predict(X_test)

In [49]:
print(confusion_matrix(y_test,y_pred_poly))
print(classification_report(y_test,y_pred_poly))

[[77  1]
 [16  8]]
              precision    recall  f1-score   support

           0       0.83      0.99      0.90        78
           1       0.89      0.33      0.48        24

    accuracy                           0.83       102
   macro avg       0.86      0.66      0.69       102
weighted avg       0.84      0.83      0.80       102



# Sigmoid

In [52]:
clf_sigmoid=SVC(kernel='sigmoid')
clf_sigmoid.fit(X_train,y_train)

SVC(kernel='sigmoid')

In [54]:
y_pred_sigmoid=clf_sigmoid.predict(X_test)

In [55]:
print(confusion_matrix(y_test,y_pred_sigmoid))
print(classification_report(y_test,y_pred_sigmoid))

[[77  1]
 [18  6]]
              precision    recall  f1-score   support

           0       0.81      0.99      0.89        78
           1       0.86      0.25      0.39        24

    accuracy                           0.81       102
   macro avg       0.83      0.62      0.64       102
weighted avg       0.82      0.81      0.77       102

